# .github/workflows/scrape.yml
name: Scrape Manga Daily

on:
  schedule:
    - cron: '0 12 * * *'  # Setiap hari jam 12:00 UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python scrape_manga.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: manga-progress
          path: |
            manga/
            state.json
            manga_metadata.json