name: Scrape Manga

on:
  schedule:
    - cron: '0 18 * * *'  # Setiap hari jam 18:00 UTC
  workflow_dispatch:      # Manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python scrape_manga.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: manga-data
          path: |
            manga/
            manga_metadata.json